
import React, { useState, useEffect } from 'react';
import { WebsiteData, SectionType } from './types';
import EditorSidebar from './components/EditorSidebar';
import Canvas from './components/Canvas';
import AIChatBot from './components/AIChatBot';
import Loader from './components/ui/Loader';
import Login from './components/Login';
import CodePanel from './components/CodePanel';
import { generateInitialWebsite } from './services/geminiService';

const INITIAL_STATE: WebsiteData = {
  name: "nuttyinc web ai Site",
  description: "A beautiful website generated by Gemini AI",
  theme: {
    primaryColor: "#4f46e5",
    secondaryColor: "#10b981",
    fontFamily: "Inter",
    mode: "light"
  },
  sections: []
};

function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [website, setWebsite] = useState<WebsiteData>(INITIAL_STATE);
  const [isStarted, setIsStarted] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState('Generating your masterpiece...');
  const [isCodeOpen, setIsCodeOpen] = useState(true);

  const handleCreate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setLoadingMessage("Architecting your website layout...");
    
    try {
      const data = await generateInitialWebsite(prompt);
      setWebsite(data);
      setIsStarted(true);
    } catch (error) {
      alert("Failed to generate website. Please try a different prompt.");
    } finally {
      setLoading(false);
    }
  };

  if (!isLoggedIn) {
    return <Login onLogin={() => setIsLoggedIn(true)} />;
  }

  if (!isStarted) {
    return (
      <div className="min-h-screen bg-slate-900 flex flex-col items-center justify-center p-6 font-outfit text-white relative overflow-hidden">
        {/* User Nav */}
        <div className="absolute top-6 right-6 flex items-center gap-4 z-20">
            <div className="text-right hidden sm:block">
                <div className="text-xs font-bold text-white">Trial Account</div>
                <div className="text-[10px] text-indigo-400">Pro Features Enabled</div>
            </div>
            <button onClick={() => setIsLoggedIn(false)} className="w-10 h-10 rounded-full bg-white/10 hover:bg-red-500/20 hover:text-red-500 border border-white/10 flex items-center justify-center transition-all">
                <i className="fa-solid fa-power-off text-sm"></i>
            </button>
        </div>

        {/* Background glow effects */}
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-indigo-600/20 blur-[120px] rounded-full"></div>
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-emerald-600/20 blur-[120px] rounded-full"></div>

        <div className="max-w-3xl w-full text-center z-10">
          <div className="mb-8 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 backdrop-blur-md">
            <span className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span>
            <span className="text-xs font-bold tracking-widest uppercase opacity-80">Powered by Gemini 3 Pro</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-black mb-8 leading-tight">
            Build your dream site <br/>
            <span className="bg-gradient-to-r from-indigo-400 to-emerald-400 bg-clip-text text-transparent">with pure magic.</span>
          </h1>
          
          <p className="text-xl text-slate-400 mb-12 max-w-xl mx-auto leading-relaxed">
            Describe your business, hobby, or project in natural language. Our AI transforms your thoughts into a professional website in seconds.
          </p>

          <div className="relative max-w-2xl mx-auto mb-16">
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. A landing page for a boutique organic coffee roastery in Seattle..."
              className="w-full h-32 p-6 rounded-2xl bg-white/5 border border-white/10 text-white placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all text-lg resize-none"
            />
            <button
              onClick={handleCreate}
              disabled={loading || !prompt.trim()}
              className="absolute bottom-4 right-4 bg-indigo-600 hover:bg-indigo-500 text-white px-8 py-3 rounded-xl font-bold transition-all transform hover:scale-105 active:scale-95 disabled:opacity-50 flex items-center gap-2"
            >
              {loading ? <i className="fa-solid fa-spinner animate-spin"></i> : <i className="fa-solid fa-wand-magic-sparkles"></i>}
              Generate Site
            </button>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 opacity-60">
            <div className="flex flex-col items-center">
                <i className="fa-solid fa-bolt-lightning text-2xl mb-2"></i>
                <span className="text-xs uppercase font-bold tracking-wider">Instant</span>
            </div>
            <div className="flex flex-col items-center">
                <i className="fa-solid fa-palette text-2xl mb-2"></i>
                <span className="text-xs uppercase font-bold tracking-wider">Customizable</span>
            </div>
            <div className="flex flex-col items-center">
                <i className="fa-solid fa-mobile-screen text-2xl mb-2"></i>
                <span className="text-xs uppercase font-bold tracking-wider">Responsive</span>
            </div>
            <div className="flex flex-col items-center">
                <i className="fa-solid fa-brain text-2xl mb-2"></i>
                <span className="text-xs uppercase font-bold tracking-wider">Intelligent</span>
            </div>
          </div>
        </div>
        
        {loading && <Loader message={loadingMessage} />}
      </div>
    );
  }

  return (
    <div className="flex h-screen w-full bg-slate-100 overflow-hidden">
      <EditorSidebar website={website} setWebsite={setWebsite} />
      <CodePanel 
        data={website} 
        isOpen={isCodeOpen} 
        onToggle={() => setIsCodeOpen(!isCodeOpen)} 
      />
      <Canvas website={website} />
      <AIChatBot 
        website={website} 
        setWebsite={setWebsite} 
        setLoading={setLoading} 
        setLoadingMessage={setLoadingMessage} 
      />
      {loading && <Loader message={loadingMessage} />}
    </div>
  );
}

export default App;
